spring:
  application:
    name: order-service
  h2:
    console.enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: password
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    cloud:
      function:
        definition: sendOrder
      stream:
        function:
          bindings:
            supplyOrder-out-0: order-send
        bindings:
          order-send:
            destination: order-channel


eureka:
  client:
    service-url:
      #      defaultZone: http://127.0.0.1:${server.port}/eureka/eureka/
      defaultZone: http://localhost:8888/eureka/


server:
  port: 8084   # HTTP (Tomcat) port