spring:
  application:
    name: counter-service


eureka:
  client:
    service-url:
      #      defaultZone: http://127.0.0.1:${server.port}/eureka/eureka/
      defaultZone: http://localhost:8888/eureka/


server:
  port: 8083   # HTTP (Tomcat) port